PLANTS = [
    {
        "id": 1,
        "name": "Paşa Kılıcı",
        "latin_name": "Sansevieria trifasciata",
        "image": "snake_plant.jpg",
        "light_level": 1,
        "water_level": 1,
        "light": "Düşük - Orta Işık. Doğrudan güneş almasa da yaşar.",
        "placement": "Yatak odası veya banyo gibi az ışık alan köşeler için idealdir. Cereyandan uzak tutulmalıdır.",
        "water": "2-3 haftada bir.",
        "watering_detail": "Toprağın tamamen kuruduğundan emin olun (parmağınızı 5 cm daldırın). Suyu doğrudan toprağa verin, yaprakların ortasına su kaçırmayın.",
        "soil": "Geçirgen, kumlu ve kaktüs karışımlı toprak.",
        "category": "Düşük Işık",
        "summary": "Hava temizleme özelliğiyle bilinen, bakımı en kolay bitkilerden biridir.",
        "supplements": "İlkbahar ve yaz aylarında ayda bir kez sıvı sukulent gübresi.",
        "traits": ["Uzun ve dik yapraklar", "Sert doku", "Koyu yeşil/Sarı kenar"],
        "keywords": ["paşa kılıcı", "kılıç", "pasa", "snake plant", "sansevieria", "mother in laws tongue", "kilic"]
    },
    {
        "id": 2,
        "name": "Deve Tabanı",
        "latin_name": "Monstera deliciosa",
        "image": "monstera.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Dolaylı Parlak Işık. Yaprak delikleri için ışık şarttır.",
        "placement": "Salonda, pencereden 1-2 metre uzaklıkta, aydınlık ama güneşin kavurmadığı bir köşe.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak üstü kuruduğunda sulayın. Büyük yapraklarını nemli bir bezle silmek tozlanmayı önler ve bitkinin nefes almasını sağlar.",
        "soil": "Torflu, drenajı yüksek toprak.",
        "category": "Tropikal",
        "summary": "Büyük, delikli yapraklarıyla salonlara egzotik bir hava katar.",
        "supplements": "Gelişim döneminde 2 haftada bir dengeli gübre.",
        "traits": ["Büyük delikli yapraklar", "Kalp formlu", "Tırmanıcı gövde"],
        "keywords": ["monstera", "deve tabanı", "delikli", "swiss cheese plant", "monstera deliciosa", "deve tabani"]
    },
    {
        "id": 3,
        "name": "Barış Çiçeği",
        "latin_name": "Spathiphyllum",
        "image": "peace_lily.jpg",
        "light_level": 1,
        "water_level": 3,
        "light": "Düşük - Orta Işık. Yarı gölge alanları sever.",
        "placement": "Mutfak veya çalışma masası gibi nemin biraz daha yüksek olduğu, doğrudan güneş görmeyen kuytu köşeler.",
        "water": "Haftada 1-2 kez.",
        "watering_detail": "Yapraklar aşağı sarkmaya başladığında sulama vaktidir. Toprağın her yerinin ıslandığından emin olun ama saksı tabağında su bırakmayın.",
        "soil": "Nem tutan, zengin içerikli toprak.",
        "category": "Çiçekli",
        "summary": "Zarif beyaz çiçekleri ve parlak yeşil yapraklarıyla şıktır.",
        "supplements": "Çiçeklenme döneminde ayda bir sıvı besin.",
        "traits": ["Beyaz yelken çiçekler", "Koyu yeşil parlak yaprak", "Hassas gövde"],
        "keywords": ["beyaz çiçek", "yelken", "baris", "peace lily", "spathiphyllum", "barış çiçeği"]
    },
    {
        "id": 4,
        "name": "Para Ağacı",
        "latin_name": "Crassula ovata",
        "image": "jade_plant.jpg",
        "light_level": 3,
        "water_level": 1,
        "light": "Parlak, Direkt Güneş.",
        "placement": "Güneş alan güney cephe pencereleri, balkon önleri veya bol ışıklı kış bahçeleri.",
        "water": "2 haftada bir.",
        "watering_detail": "Yapraklar buruşmaya başladığında su ister. Kışın sulama ayda bire düşürülmelidir. Fazla su kökleri anında çürütür.",
        "soil": "Kaktüs/Sukulent toprağı.",
        "category": "Sukulent",
        "summary": "Etli yaprakları olan, dayanıklı bir sukulent türüdür.",
        "supplements": "Büyüme mevsiminde ayda bir sukulent gübresi.",
        "traits": ["Etli küçük yapraklar", "Odunsu gövde", "Parlak yeşil"],
        "keywords": ["para", "jade", "etli yaprak", "crassula", "money tree", "lucky plant", "para ağacı"]
    },
    {
        "id": 5,
        "name": "Aşk Merdiveni",
        "latin_name": "Nephrolepis exaltata",
        "image": "fern.jpg",
        "light_level": 2,
        "water_level": 3,
        "light": "Dolaylı Işık. Nemli banyoları sever.",
        "placement": "Nemin yüksek olduğu banyolar veya mutfak rafları. Cereyandan nefret eder, sabit yer sever.",
        "water": "Sık sulama.",
        "watering_detail": "Toprağı her zaman nemli olmalı ama çamurlaşmamalıdır. Yazın her gün fısfıs ile yapraklarına su sıkılmalıdır.",
        "soil": "Havadar, humuslu toprak.",
        "category": "Nem Sever",
        "summary": "Yüksek nem seven, sarkık formlu bir eğrelti otu türüdür.",
        "supplements": "Yaz aylarında 2 haftada bir yarı dozda gübre.",
        "traits": ["Tüysü ince yapraklar", "Sarkık form", "Yoğun yeşil"],
        "keywords": ["merdiven", "egrelti", "fern", "boston fern", "nephrolepis", "aşk merdiveni"]
    },
    {
        "id": 6,
        "name": "Aloe Vera",
        "latin_name": "Aloe barbadensis Miller",
        "image": "aloe_vera.jpg",
        "light_level": 3,
        "water_level": 1,
        "light": "Parlak Güneş.",
        "placement": "Doğrudan güneş gören cam önleri. Güneş görmezse yaprakları cılızlaşır ve sarkar.",
        "water": "3 haftada bir.",
        "watering_detail": "Sulamadan önce toprağın saksı dibine kadar kuruduğundan emin olun. Kışın hiç sulanmasa bile hayatta kalabilir.",
        "soil": "Kaktüs toprağı.",
        "category": "Sukulent",
        "summary": "Tıbbi amaçlarla kullanılan jeliyle ünlü, bakımı kolaydır.",
        "supplements": "Yılda bir kez ilkbaharda gübre.",
        "traits": ["Dikenli kenarlar", "Etli uzun yaprak", "Gri-yeşil tonlar"],
        "keywords": ["aloe", "vera", "sifali", "tıbbi sarısabır", "aloe barbadensis"]
    },
    {
        "id": 7,
        "name": "Dua Çiçeği",
        "latin_name": "Maranta leuconeura",
        "image": "prayer_plant.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Yarı Gölge.",
        "placement": "Direkt güneşten uzak, kuzey cephe pencereleri veya oda içindeki raflar.",
        "water": "Haftada 2 kez.",
        "watering_detail": "Toprak yüzeyi kurumaya başladığında kireçsiz oda sıcaklığında su ile sulayın. Akşamları yapraklarının kapanması normaldir.",
        "soil": "Nemi koruyan toprak.",
        "category": "Yaprak Güzeli",
        "summary": "Gece yapraklarını kapatmasıyla bilinir, desenli yaprakları harikadır.",
        "supplements": "Gelişim mevsiminde ayda bir sıvı gübre.",
        "traits": ["Kapanan yapraklar", "Desenli yaprak", "Nem sever"],
        "keywords": ["dua", "maranta", "prayer plant", "leuconeura", "dua çiçeği"]
    },
    {
        "id": 8,
        "name": "Kurdele Çiçeği",
        "latin_name": "Chlorophytum comosum",
        "image": "spider_plant.jpg",
        "light_level": 1,
        "water_level": 2,
        "light": "Orta Işık.",
        "placement": "Her türlü ortama uyum sağlar ancak askılı saksılarda tavandan sarkıtılması yavruları için harikadır.",
        "water": "Haftada bir.",
        "watering_detail": "Yazın haftada iki, kışın haftada bir sulayın. Yaprak uçları kahverengileşirse havadaki nem az demektir, su püskürtün.",
        "soil": "Standart saksı toprağı.",
        "category": "Düşük Işık",
        "summary": "Havadaki toksinleri temizleyen, yavru veren dayanıklı bir bitkidir.",
        "supplements": "Ayda bir dengeli gübre.",
        "traits": ["İnce uzun yaprak", "Yavru verme", "Hava temizleme"],
        "keywords": ["kurdele", "orumcek", "spider plant", "chlorophytum", "kurdele çiçeği"]
    },
    {
        "id": 9,
        "name": "Kauçuk Ağacı",
        "latin_name": "Ficus elastica",
        "image": "rubber_plant.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Salonda köşe kısımlar, pencereye yakın ama güneş ışınlarının dik gelmediği noktalar.",
        "water": "Toprak kurudukça.",
        "watering_detail": "Toprağın üstü kuruduğunda doyurucu sulama yapın. Fazla su yaprak dökmesine neden olur. Yapraklarını düzenli silin.",
        "soil": "Drenajı iyi toprak.",
        "category": "Tropikal",
        "summary": "Koyu parlak yapraklarıyla dramatik bir iç mekan bitkisidir.",
        "supplements": "Yazın 2 haftada bir gübre.",
        "traits": ["Koyu parlak yaprak", "Geniş yaprak", "Ağaçsı form"],
        "keywords": ["kaucuk", "ficus", "rubber tree", "ficus elastica", "rubber plant", "kauçuk ağacı"]
    },
    {
        "id": 10,
        "name": "Zeze Çiçeği",
        "latin_name": "Zamioculcas zamiifolia",
        "image": "zz_plant.jpg",
        "light_level": 1,
        "water_level": 1,
        "light": "Çok Düşük - Orta Işık.",
        "placement": "Hiç penceresi olmayan ofisler veya evin en karanlık köşeleri için tek seçenektir.",
        "water": "Ayda bir.",
        "watering_detail": "Saksı tamamen hafiflediğinde sulayın. Su vermeyi unutsanız bile aylar boyunca canlı kalabilir.",
        "soil": "Kum karışımlı toprak.",
        "category": "Düşük Işık",
        "summary": "İhmal edilmeye en dayanıklı, 'ölümsüz' bitkidir.",
        "supplements": "Yılda 1-2 kez gübre.",
        "traits": ["Mumsu parlak yapraklar", "Etli gövde", "Koyu yeşil"],
        "keywords": ["zeze", "zz plant", "zamioculcas", "zanzibar gem", "zeze çiçeği"]
    },
    {
        "id": 11,
        "name": "Salon Palmiyesi",
        "latin_name": "Chamaedorea elegans",
        "image": "parlor_palm.jpg",
        "light_level": 1,
        "water_level": 2,
        "light": "Düşük - Orta Işık.",
        "placement": "Aydınlık ama doğrudan güneş almayan sehpa üzerleri veya kitaplık rafları.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak kurumaya yakınken sulayın. Köklerin suda kalmasını sevmez, fazla suyu saksı tabağından mutlaka dökün.",
        "soil": "Genel amaçlı toprak.",
        "category": "Palmiye",
        "summary": "Zarif yaprakları ve yavaş büyüme hızıyla idealdir.",
        "supplements": "İlkbahar ve yazın ayda bir sıvı gübre.",
        "traits": ["İnce uzun yapraklar", "Çoklu gövde", "Zarif duruş"],
        "keywords": ["palmiye", "salon", "parlor palm", "chamaedorea", "salon palmiyesi"]
    },
    {
        "id": 12,
        "name": "Salon Sarmaşığı",
        "latin_name": "Epipremnum aureum",
        "image": "pothos.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Düşük - Parlak Dolaylı.",
        "placement": "Gardırop üstleri veya askılı saksılar. Yapraklarının aşağı sarkması için yükseğe konulmalıdır.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak kuruduğunda sulayın. Çok dayanıklıdır, su dolu bir vazoda toprak olmadan da yıllarca yaşayabilir.",
        "soil": "Standart toprak.",
        "category": "Sarmaşık",
        "summary": "Sarkık formda yetişen, hava temizleyici türüdür.",
        "supplements": "Ayda bir kez gübreleme.",
        "traits": ["Kalp şeklinde yapraklar", "Sarkıcı/Tırmanıcı", "Hızlı gelişim"],
        "keywords": ["sarmasik", "pothos", "ivy", "epipremnum", "golden pothos", "salon sarmaşığı"]
    },
    {
        "id": 13,
        "name": "Orkide",
        "latin_name": "Phalaenopsis",
        "image": "orchid.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Dolaylı Işık, Aydınlık.",
        "placement": "Doğu veya batı penceresi önü, tül arkasından gelen süzülmüş ışık. Soğuk cereyandan hemen etkilenir.",
        "water": "Haftada bir (Daldırma).",
        "watering_detail": "Saksıyı su dolu bir kaba koyun, 15-20 dakika bekletin ve sonra suyunu tamamen süzün. Köklerin griye dönmesi sulama zamanıdır.",
        "soil": "Özel orkide kabuğu.",
        "category": "Çiçekli",
        "summary": "Zarif çiçekleri ve uzun çiçeklenme süresiyle popülerdir.",
        "supplements": "Çiçeklenme sonrası özel gübre.",
        "traits": ["Zarif çiçekler", "Havadar kökler", "Etli geniş yaprak"],
        "keywords": ["orkide", "orchid"]
    },
    {
        "id": 14,
        "name": "Afrika Menekşesi",
        "latin_name": "Saintpaulia",
        "image": "african_violet.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Orta - Parlak Dolaylı.",
        "placement": "Mutfak penceresi gibi aydınlık ama serin yerler. Yapraklarına su değerse leke kalır.",
        "water": "Toprak kurudukça.",
        "watering_detail": "Alttan sulama yapın (tabağına su koyup 20 dk bekletin). Asla yapraklarına su püskürtmeyin, mantar yapar.",
        "soil": "Menekşe toprağı.",
        "category": "Çiçekli",
        "summary": "Kadifemsi yapraklı küçük bir saksı bitkisidir.",
        "supplements": "Ayda bir menekşe gübresi.",
        "traits": ["Kadife yapraklar", "Küçük form", "Mor/Renkli çiçek"],
        "keywords": ["menekse"]
    },
    {
        "id": "medinilla_magnifica",
        "name": "Medine Gülü",
        "latin_name": "Medinilla magnifica",
        "image": "medinilla_magnifica.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık. Doğrudan güneş ışığı yapraklarını yakabilir.",
        "placement": "Yüksek nemli, havadar ve aydınlık salon köşeleri. Tropikal bir prenses olduğu için neme bayılır ama cereyandan nefret eder.",
        "water": "Haftada 1 kez.",
        "watering_detail": "Toprak yüzeyi hafifçe kuruduğunda sulayın. Kışın sulamayı azaltın. Çiçek salkımları oluşurken neme ekstra ihtiyaç duyar.",
        "soil": "Havadar, orkide toprağı ve torf karışımlı zengin toprak.",
        "category": "Egzotik / Çiçekli",
        "summary": "Görkemli pembe salkım çiçekleriyle 'Bitki Krallığı'nın en lüks üyelerinden biridir.",
        "supplements": "Çiçeklenme döneminde 2 haftada bir yüksek fosforlu sıvı gübre veya orkide besini.",
        "traits": ["Dev salkım pembe çiçekler", "Kalın damarlı geniş yapraklar", "Egzotik form"],
        "keywords": ["medine", "gulu", "medinilla", "magnifica", "pembe salkım"]
    },
    {
        "id": 16,
        "name": "Benjamin",
        "latin_name": "Ficus benjamina",
        "image": "weeping_fig.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Sabit bir yer sever. Yerini değiştirirseniz yaprak döker. Aydınlık koridorlar için uygundur.",
        "water": "Toprak üstü kurudukça.",
        "watering_detail": "Yazın sık, kışın seyrek sulayın. Toprağının asla tamamen kurumasına izin vermeyin ama kökleri de boğmayın.",
        "soil": "Zengin saksı toprağı.",
        "category": "Ağaç Formlu",
        "summary": "Küçük yaprakları ve ağaç formuyla salonların klasiğidir.",
        "supplements": "2 haftada bir sıvı gübre.",
        "traits": ["Küçük parlak yaprak", "Ağaç formu", "Sık dallar"],
        "keywords": ["benjamin"]
    },
    {
        "id": 36,
        "name": "Antoryum",
        "latin_name": "Anthurium andraeanum",
        "image": "anthurium.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Aydınlık ama güneşin yakmadığı nemli odalar. Çiçeklerin kalıcılığı için ışık şarttır.",
        "water": "Haftada 1-2 kez.",
        "watering_detail": "Toprağın nemini koruyun. Yazın yapraklarına su püskürtülmesini çok sever. Kışın sulama azaltılmalıdır.",
        "soil": "Havadar toprak.",
        "category": "Çiçekli",
        "summary": "Kırmızı parlak çiçekleriyle egzotiktir.",
        "supplements": "Ayda bir çiçekli bitki gübresi.",
        "traits": ["Parlak kırmızı çiçek", "Kalp yaprak", "Mumsu doku"],
        "keywords": ["antoryum"]
    },
    {
        "id": 17,
        "name": "Kroton",
        "latin_name": "Codiaeum variegatum",
        "image": "croton.jpg",
        "light_level": 3,
        "water_level": 2,
        "light": "Çok Parlak Dolaylı.",
        "placement": "Doğrudan güneş alabilen pencere önleri. Işık az olursa yaprak renkleri solar.",
        "water": "Nemli tutulmalı.",
        "watering_detail": "Toprak kurumaya başladığında bol su verin. Yazın her gün yapraklarına su püskürtmek renk canlılığını artırır.",
        "soil": "Drenajlı toprak.",
        "category": "Renkli Yaprak",
        "summary": "Renkli yapraklarıyla görsel şölen sunar.",
        "supplements": "Ayda bir gübre.",
        "traits": ["Renkli damarlı yaprak", "Sarı/Turuncu/Kırmızı", "Sert yaprak"],
        "keywords": ["kroton"]
    },
    {
        "id": 18,
        "name": "Drasena",
        "latin_name": "Dracaena marginata",
        "image": "dracaena.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Orta - Parlak Dolaylı.",
        "placement": "Evin her yeri için uygundur ama orta derece aydınlık köşelerde daha hızlı büyür.",
        "water": "10 günde bir.",
        "watering_detail": "Toprak iyice kurumadan sulamayın. Musluk suyundaki kirece hassastır, dinlenmiş su kullanmanız önerilir.",
        "soil": "Standart toprak.",
        "category": "Palmiye Formlu",
        "summary": "İnce uzun yapraklarıyla dekoratiftir.",
        "supplements": "Yazın ayda bir gübre.",
        "traits": ["İnce uzun yaprak", "Odunsu gövde", "Dik duruş"],
        "keywords": ["drasena"]
    },
    {
        "id": 19,
        "name": "Begonya",
        "latin_name": "Begonia",
        "image": "begonia.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Yarı Gölge.",
        "placement": "Direkt güneş almayan ama aydınlık olan serin oda köşeleri. Nemli ortamları sever.",
        "water": "Haftada 2 kez.",
        "watering_detail": "Toprak üstü hafif kuruduğunda sulayın. Yapraklarına su değdirmemeye çalışın, aksi halde lekeler oluşabilir.",
        "soil": "Humuslu toprak.",
        "category": "Çiçekli",
        "summary": "Hem yaprak hem çiçek güzelliği sunar.",
        "supplements": "Sıvı gübre.",
        "traits": ["Asimetrik yapraklar", "Narin çiçekler", "Desenli yaprak"],
        "keywords": ["begonya"]
    },
    {
        "id": 20,
        "name": "Siklamen",
        "latin_name": "Cyclamen",
        "image": "cyclamen.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Serin ve Aydınlık.",
        "placement": "Kışın serin balkonlar veya kaloriferden uzak soğuk oda pencereleri. Sıcağı hiç sevmez.",
        "water": "Nemli tutulmalı.",
        "watering_detail": "Saksı tabağından sulama yapın. Çiçeklerine ve gövdesine su gelirse hemen çürür. Toprak hep nemli kalmalı.",
        "soil": "Geçirgen toprak.",
        "category": "Kış Çiçeği",
        "summary": "Kış aylarında açan çiçekleriyle ünlüdür.",
        "supplements": "Çiçeklenme süresince gübre.",
        "traits": ["Kalp şeklinde yaprak", "Yukarı dönük çiçek", "Serin sever"],
        "keywords": ["siklamen"]
    },
    {
        "id": 21,
        "name": "Kalanşo",
        "latin_name": "Kalanchoe blossfeldiana",
        "image": "kalanchoe.jpg",
        "light_level": 2,
        "water_level": 1,
        "light": "Parlak Işık.",
        "placement": "Aydınlık cam önleri. Çiçek tomurcukları için bol güneş ışığına ihtiyaç duyar.",
        "water": "2 haftada bir.",
        "watering_detail": "Toprak taş gibi kurumadan sulamayın. Etli yapraklarında su depolar, bu yüzden az su ile aylarca mutlu kalır.",
        "soil": "Sukulent toprağı.",
        "category": "Sukulent",
        "summary": "Dayanıklı ve çiçekli bir sukulenttir.",
        "supplements": "Bahar aylarında gübre.",
        "traits": ["Etli yaprak", "Küçük çiçek kümeleri", "Kompakt form"],
        "keywords": ["kalanso"]
    },
    {
        "id": 22,
        "name": "Mum Çiçeği",
        "latin_name": "Hoya carnosa",
        "image": "hoya.jpg",
        "light_level": 2,
        "water_level": 1,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Yüksek raflar veya pencere kenarları. Çiçek açması için günde 2-3 saat sabah güneşi alması iyidir.",
        "water": "Toprak kurudukça.",
        "watering_detail": "Yaprakları sertleştiğinde sulayın. Kışın sulamayı en aza indirin. Çiçek saplarını asla kesmeyin, seneye oradan açar.",
        "soil": "Geçirgen toprak.",
        "category": "Sarmaşık",
        "summary": "Yıldız şeklindeki kokulu çiçekleriyle bilinir.",
        "supplements": "Yazın ayda bir gübre.",
        "traits": ["Yıldız şeklinde çiçek", "Etli yaprak", "Sarmaşık form"],
        "keywords": ["mum çiçeği", "hoya"]
    },
    {
        "id": 23,
        "name": "Telgraf Çiçeği",
        "latin_name": "Tradescantia zebrina",
        "image": "tradescantia.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Kitaplık rafları veya sarkan saksılar. Işık azsa yapraklarındaki mor renk yeşile döner.",
        "water": "Haftada 1-2 kez.",
        "watering_detail": "Toprağın nemini koruyun. Yazın sulama arasını açın.",
        "soil": "Genel amaçlı toprak.",
        "category": "Sarmaşık",
        "summary": "Mor ve gümüş çizgili yapraklarıyla hızlı büyür.",
        "supplements": "Ayda bir gübreleme.",
        "traits": ["Mor çizgili yaprak", "Sarkık form", "Zebra deseni"],
        "keywords": ["telgraf", "zebra"]
    },
    {
        "id": 24,
        "name": "Şans Bambusu",
        "latin_name": "Dracaena sanderiana",
        "image": "lucky_bamboo.jpg",
        "light_level": 1,
        "water_level": 3,
        "light": "Düşük - Orta Işık.",
        "placement": "Doğrudan güneş almayan masalar veya banyo tezgahları. Vazoda su içinde bakılabilir.",
        "water": "Suda yetiştirilebilir.",
        "watering_detail": "Vazodaki suyu 10 günde bir tazeleyin. Musluk suyu yerine içme suyu kullanmanız sararmaları önler.",
        "soil": "Su veya toprak.",
        "category": "Düşük Işık",
        "summary": "Şans getirdiğine inanılan dayanıklı bir bitkidir.",
        "supplements": "Suda yetişiyorsa ayda bir damla gübre.",
        "traits": ["Çubuk form", "Yeşil boğumlu gövde", "Suya dayanıklı"],
        "keywords": ["bambu", "şans"]
    },
    {
        "id": 25,
        "name": "Çin Herdemyeşili",
        "latin_name": "Aglaonema",
        "image": "aglaonema.jpg",
        "light_level": 1,
        "water_level": 2,
        "light": "Düşük - Orta Dolaylı Işık.",
        "placement": "Evin az ışık alan girişleri veya yatak odaları için en uyumlu bitkilerden biridir.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak yüzeyi kuruduğunda sulayın. Yazın nemli tutun, kışın ise sulama arasını açın.",
        "soil": "Drenajlı toprak.",
        "category": "Düşük Işık",
        "summary": "Gümüş desenli yapraklarıyla gölge alanları canlandırır.",
        "supplements": "Seyreltilmiş sıvı gübre.",
        "traits": ["Desenli geniş yaprak", "Gümüş/Yeşil tonlar", "Kısa gövde"],
        "keywords": ["aglaonema", "çin herdem"]
    },
    {
        "id": 26,
        "name": "Yıldız Çiçeği",
        "latin_name": "Cryptanthus",
        "image": "cryptanthus.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Orta - Parlak Dolaylı.",
        "placement": "Yüksek nemli alanlar (Banyo vb.). Terraryumlar için çok uygundur.",
        "water": "Nemli tutulmalı.",
        "watering_detail": "Toprağının nemli kalmasına dikkat edin. Rozet şeklindeki merkezine su kaçırmamaya çalışın.",
        "soil": "Bromeliad toprağı.",
        "category": "Egzotik",
        "summary": "Yıldız şeklindeki rozet yapısıyla dikkat çeker.",
        "supplements": "Ayda bir yapraktan gübreleme.",
        "traits": ["Yıldız rozet", "Zikzak desenli yaprak", "Yer örtücü form"],
        "keywords": ["cryptanthus", "yıldız"]
    },
    {
        "id": 27,
        "name": "Kalp Yapraklı Filodendron",
        "latin_name": "Philodendron hederaceum",
        "image": "heartleaf_philodendron.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Düşük - Orta Dolaylı Işık.",
        "placement": "Pencereden uzak iç duvarlar veya kitaplıklar. Çok gölgeyi bile tolere edebilir.",
        "water": "Haftada bir.",
        "watering_detail": "Toprağın üstü kuruduğunda sulayın. Çok fazla su yaprakların sararmasına neden olur.",
        "soil": "Humuslu toprak.",
        "category": "Sarmaşık",
        "summary": "Kalp şeklindeki yapraklarıyla en sevilen sarmaşıktır.",
        "supplements": "Yazın ayda bir gübre.",
        "traits": ["Net kalp şekli", "İnce uzun dallar", "Pürüzsüz yaprak"],
        "keywords": ["philodendron", "kalp yaprak"]
    },
    {
        "id": 28,
        "name": "N-Joy Sarmaşığı",
        "latin_name": "Epipremnum aureum 'N-Joy'",
        "image": "njoy_pothos.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Orta - Parlak Dolaylı.",
        "placement": "Aydınlık ama doğrudan güneş almayan raflar. Beyaz kısımların canlı kalması için ışık almalıdır.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak yüzeyi kuruduğunda sulama yapın. Aşırı sulama yapraklarda siyah leke yapabilir.",
        "soil": "Geçirgen toprak.",
        "category": "Sarmaşık",
        "summary": "Beyaz-yeşil lekeli yapraklarıyla Pothos varyetesidir.",
        "supplements": "Ayda bir gelişim gübresi.",
        "traits": ["Beyaz-Yeşil alacalı", "Küçük yaprak", "Kompakt büyüme"],
        "keywords": ["njoy", "pothos", "alacalı"]
    },
    {
        "id": 29,
        "name": "Mini Monstera",
        "latin_name": "Rhaphidophora tetrasperma",
        "image": "rhaphidophora.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Parlak Dolaylı Işık.",
        "placement": "Tırmanabilmesi için bir çubuk veya duvar kenarı. Aydınlık bir salon köşesi idealdir.",
        "water": "Haftada 1-2 kez.",
        "watering_detail": "Hızlı büyüdüğü için suya ihtiyacı vardır ancak toprağı çamur etmeyin. Düzenli olarak fısfıslayın.",
        "soil": "Zengin drenajlı toprak.",
        "category": "Tropikal",
        "summary": "Deve tabanına benzeyen hızlı tırmanan egzotik türdür.",
        "supplements": "2 haftada bir azotlu gübre.",
        "traits": ["Parçalı küçük yaprak", "Hızlı tırmanıcı", "Egzotik form"],
        "keywords": ["rhaphidophora", "mini monstera"]
    },
    {
        "id": 30,
        "name": "Gardenya",
        "latin_name": "Gardenia jasminoides",
        "image": "gardenia.jpg",
        "light_level": 3,
        "water_level": 3,
        "light": "Parlak Dolaylı Işık. Sabah güneşini sever.",
        "placement": "Evin en havadar ve aydınlık, serin odası. Sıcak ve kuru havadan hiç hoşlanmaz.",
        "water": "Toprak hep nemli tutulmalı.",
        "watering_detail": "Toprak kurumaya fırsat bulmadan ama boğmadan sulayın. Yapraklarına su püskürtülmesini çok sever ancak tomurcuklara gelmemeli.",
        "soil": "Asidik, humuslu toprak.",
        "category": "Çiçekli",
        "summary": "Muhteşem kokulu beyaz çiçekleriyle bilinen, asil bir salon bitkisidir.",
        "supplements": "Ayda bir asidik bitki gübresi.",
        "traits": ["Kokulu beyaz çiçek", "Parlak koyu yeşil yaprak", "Kalıcı yaprak"],
        "keywords": ["gardenya", "kokulu", "beyaz"]
    },
    {
        "id": 31,
        "name": "Atatürk Çiçeği",
        "latin_name": "Euphorbia pulcherrima",
        "image": "poinsettia.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Aydınlık ama doğrudan güneş almayan yer.",
        "placement": "Sabit sıcaklığı olan, cereyandan uzak bir nokta. Kışın ısıtıcılardan uzak tutulmalıdır.",
        "water": "Toprak kurudukça.",
        "watering_detail": "Parmağınızla kontrol edip toprak kuruysa sulayın. Alttan sulama yapmak her zaman daha güvenlidir.",
        "soil": "Havadar, drenajlı toprak.",
        "category": "Çiçekli",
        "summary": "Kırmızı yapraklarıyla (brakte) kış aylarının vazgeçilmez simgesidir.",
        "supplements": "Çiçeklenme sonrası ayda bir kez gübre.",
        "traits": ["Geniş kırmızı yapraklar", "Sütlü gövde", "Kışın çiçeklenme"],
        "keywords": ["ataturk", "poinsettia", "kirmizi"]
    },
    {
        "id": 32,
        "name": "Yılbaşı Kaktüsü",
        "latin_name": "Schlumbergera",
        "image": "christmas_cactus.jpg",
        "light_level": 2,
        "water_level": 2,
        "light": "Yarı Gölge / Aydınlık.",
        "placement": "Doğu pencereleri veya evin aydınlık, serin kısımları. Tomurcuklanma için serinliğe ihtiyaç duyar.",
        "water": "Haftada bir.",
        "watering_detail": "Toprak üstü hafifçe kuruduğunda sulayın. Çiçek açtığında suyu asla eksik etmeyin, yoksa çiçeklerini döker.",
        "soil": "Geçirgen, kumlu toprak.",
        "category": "Çiçekli",
        "summary": "Kışın açan sarkık, renkli çiçekleriyle balkon ve salonları süsler.",
        "supplements": "Çiçeklenme öncesi potasyumlu gübre.",
        "traits": ["Eklemli yassı yaprak", "Sarkık form", "Canlı pembe/kırmızı çiçek"],
        "keywords": ["yilbasi", "kaktus", "pembe"]
    },
    {
        "id": 33,
        "name": "Japon Gülü (Hibiskus)",
        "latin_name": "Hibiscus rosa-sinensis",
        "image": "hibiscus.jpg",
        "light_level": 3,
        "water_level": 3,
        "light": "Bol Güneşli ve Aydınlık.",
        "placement": "Pencereye en yakın, en çok güneş alan nokta. Işıksız kalırsa çiçekleri dökülür.",
        "water": "Yazın bol su.",
        "watering_detail": "Yazın neredeyse her gün sulama ister. Saksı tabağında su bekletmeyin, bolca sulayıp fazlasını dökün.",
        "soil": "Vitaminli, bahçe toprağı karışımı.",
        "category": "Çiçekli",
        "summary": "Devasa ve göz alıcı çiçekleriyle tropikal bir hava yaratır.",
        "supplements": "15 günde bir çiçekli bitki besini.",
        "traits": ["Büyük huni çiçek", "Belirgin polen borusu", "Testere dişli yaprak"],
        "keywords": ["hibiskus", "japon gülü", "buyuk cicek"]
    },
    {
        "id": 34,
        "name": "Küpeli Çiçeği",
        "latin_name": "Fuchsia",
        "image": "fuchsia.jpg",
        "light_level": 2,
        "water_level": 3,
        "light": "Yarı Gölge. Esintili yerleri sever.",
        "placement": "Havadar balkonlar veya kuzeye bakan pencereler. Durgun ve sıcak havada hemen solar.",
        "water": "Toprak kurutulmamalı.",
        "watering_detail": "Sulamada gecikmeyin, toprağı hep nemli kalsın. Yazın sıcaklarında günde iki kez sulama gerekebilir.",
        "soil": "Geçirgen, hafif asidik toprak.",
        "category": "Çiçekli",
        "summary": "Küpeye benzeyen zarif, sarkık çiçekleriyle çok dekoratiftir.",
        "supplements": "Gelişim döneminde haftalık sıvı gübre.",
        "traits": ["Sarkık çan çiçekler", "Çift renkli taç yaprak", "Zarif dallar"],
        "keywords": ["küpeli", "fuchsia", "sarkik"]
    },
    {
        "id": 35,
        "name": "Açelya",
        "latin_name": "Rhododendron",
        "image": "azalea.jpg",
        "light_level": 2,
        "water_level": 3,
        "light": "Serin ve Aydınlık. Direkt güneşten kaçınmalı.",
        "placement": "Serin ve havadar salonlar. Kışın ısıtılmayan odaları çok sever.",
        "water": "Kökleri hep nemli kalmalı.",
        "watering_detail": "Daldırma yöntemiyle sulayın (15 dk suda bekletip süzün). Asla kireçli musluk suyu kullanmayın, yağmur suyu idealdir.",
        "soil": "Asidik funda toprağı.",
        "category": "Çiçekli",
        "summary": "Baharın müjdecisi olan, yoğun çiçek açan bir çalı formlu bitkidir.",
        "supplements": "Çiçeklenme sonrası asitli gübre.",
        "traits": ["Yoğun çiçek kümeleri", "Küçük sert yaprak", "Çalı formu"],
        "keywords": ["acelya", "azalea", "pembemsi"]
    }
]

DISEASES = [
    {
        "id": "toprak_kuruması",
        "name": "Toprak Kuruması (Susuzluk)",
        "symptoms": ["Toprağın sertleşmesi", "Yaprakların sarkması", "Kahverengi kuru uçlar"],
        "keywords": ["kuruma", "susuzluk", "kuru toprak", "solma", "gevşek", "su"],
        "cause": "Yetersiz sulama veya çok sıcak/kuru hava şartları.",
        "treatment": "Bitkiyi derinlemesine sulayın (saksı altından su çıkana kadar). Toprak nemini parmağınızla düzenli kontrol edin.",
        "tone": "Bitkiniz sadece biraz susamış, bol su ile kısa sürede canlanacaktır!"
    },
    {
        "id": "unlu_bit",
        "name": "Unlu Bit (Pamukçuk)",
        "symptoms": ["Beyaz pamuksu kümeler", "Yapışkan şekerli sıvı", "Yaprak sararması"],
        "keywords": ["beyaz", "pamuksu", "yapışkan", "bit", "pamuk"],
        "cause": "Havasız ortamlar ve bitkinin düşük bağışıklığı.",
        "treatment": "Alkol batırılmış pamuk veya arapsabunlu su ile temizleyin. Neem yağı uygulayın.",
        "tone": "O beyaz pamukçuklar bitkinizi yoruyor, temizlik vakti!"
    },
    {
        "id": "orumcek_akari",
        "name": "Örümcek Akarı",
        "symptoms": ["İnce beyaz ağlar", "Yapraklarda sarı küçük benekler"],
        "keywords": ["örümcek", "ağ", "küçük nokta", "sarı benek"],
        "cause": "Kuru ve sıcak hava şartları.",
        "treatment": "Yaprakları nemli bezle silin, ortam nemini artırın ve gerekirse neem yağı kullanın.",
        "tone": "O minik ağlar bitkinizi boğuyor, nemli bir duş ona çok iyi gelecektir."
    },
    {
        "id": "kullenme",
        "name": "Küllenme (Mantar)",
        "symptoms": ["Yapraklarda beyaz toz tabakası", "Gri kül benzeri lekeler"],
        "keywords": ["toz", "kül", "gri leke", "mantar", "beyaz toz"],
        "cause": "Yüksek nem ve yetersiz hava sirkülasyonu.",
        "treatment": "Uygun bir fungisit (mantar ilacı) kullanın ve bitkinin hava almasını sağlayın.",
        "tone": "Yaprakların üzerindeki bu pudramsı tabaka mantar kaynaklıdır, taze hava şart."
    },
    {
        "id": "pas",
        "name": "Pas Hastalığı",
        "symptoms": ["Turuncu/Kırmızı lekeler", "Yaprak altında kabarcıklar"],
        "keywords": ["turuncu", "kırmızı", "pas", "kızıl"],
        "cause": "Aşırı nem ve yaprakların uzun süre ıslak kalması.",
        "treatment": "Hastalıklı yaprakları hemen kesin ve bakır bazlı mantar ilacı uygulayın.",
        "tone": "Turuncu lekeler yayılmadan müdahale edilmelidir."
    },
    {
        "id": "kok_curumesi",
        "name": "Siyah Kök Çürüklüğü",
        "symptoms": ["Köklerde kararma/yumuşama", "Toprakta kötü koku", "Ani solma"],
        "keywords": ["kök çürümesi", "siyah kök", "çürük", "koku"],
        "cause": "Aşırı sulama ve drenajı olmayan saksı seçimi.",
        "treatment": "Sulamayı derhal kesin, toprağı değiştirin ve çürük kökleri temizleyin.",
        "tone": "Bitkinizin kökleri fazla sudan nefes alamıyor, kurumasını bekleyin."
    },
    {
        "id": "beyaz_sinek",
        "name": "Beyaz Sinek İstilası",
        "symptoms": ["Yaprak altında küçük beyaz sinekler", "Dokununca uçuşan böcekler"],
        "keywords": ["beyaz sinek", "uçan böcek", "yaprak altı"],
        "cause": "Havasız ve sıcak ortamlar.",
        "treatment": "Sarı yapışkan tuzaklar kullanın ve insektisit sabun ile bitkiyi yıkayın.",
        "tone": "Uçuşan misafirlerinizi uzaklaştırmak için doğal sabunlu su idealdir."
    },
    {
        "id": "kabuklu_bit",
        "name": "Kabuklu Bit",
        "symptoms": ["Gövdede kahverengi sert şişlikler", "Yapışkan doku"],
        "keywords": ["kabuk", "kahverengi şişlik", "sert bit", "kabuklu"],
        "cause": "Bitki özsuyunu emen asalak kabuklu böcekler.",
        "treatment": "Kabukları fırça veya alkollü pamukla fiziksel olarak temizleyin.",
        "tone": "Bu sert kabuklar bitkinizin gücünü emiyor, hemen temizlemelisiniz."
    },
    {
        "id": "antraknoz",
        "name": "Antraknoz (Leke Hastalığı)",
        "symptoms": ["Çökük kahverengi lekeler", "Gövdede yaralar"],
        "keywords": ["çökük leke", "kahverengi yara", "gövde lekesi", "yara"],
        "cause": "Colletotrichum mantarı ve aşırı yaprak ıslaklığı.",
        "treatment": "Bakır bazlı ilaçlar kullanın ve hastalıklı kısımları imha edin.",
        "tone": "Lekeler derinleşmeden müdahale ederek bitkinizi kurtarabiliriz."
    },
    {
        "id": "trips",
        "name": "Trips Zararlısı",
        "symptoms": ["Yapraklarda gümüşi çizgiler", "Parlak metalik lekeler"],
        "keywords": ["gümüş çizgi", "parlak leke", "ince böcek", "metalik"],
        "cause": "Hücre özsuyunu emen çok küçük, hızlı hareket eden böcekler.",
        "treatment": "Mavi yapışkan tuzaklar kullanın ve bitkiyi tazyikli suyla yıkayın.",
        "tone": "Gümüşi izler trips belirtisidir, bitkinize bir banyo yaptırın."
    },
    {
        "id": "mildiyo",
        "name": "Mildiyö (Beyaz Küf)",
        "symptoms": ["Yaprak altında tüylü beyaz tabaka", "Yaprak üstünde sarı lekeler"],
        "keywords": ["mildiyo", "beyaz küf", "yaprak altı tüylenme"],
        "cause": "Yüksek nem ve düşük sıcaklık farkları.",
        "treatment": "Havalandırmayı artırın, nemli ortamı azaltın ve fungisit uygulayın.",
        "tone": "Yaprakların altındaki o tüylü doku mantar kaynaklıdır, kuru tutmaya çalışın."
    },
    {
        "id": "kloroz",
        "name": "Kloroz (Demir Eksikliği)",
        "symptoms": ["Damarlar yeşil, yapraklar sarı", "Gelişim durması"],
        "keywords": ["sararma", "damar yeşil", "solgun", "demir"],
        "cause": "Toprak pH değerinin yüksek olması veya demir eksikliği.",
        "treatment": "Demir şelatı içeren sıvı gübreler verin ve toprak pH'ını dengeleyin.",
        "tone": "Bitkinizin rengi yerine gelsin diye biraz vitamin takviyesi şart."
    },
    {
        "id": "botrytis",
        "name": "Botrytis (Gri Küf)",
        "symptoms": ["Yapraklarda ve çiçeklerde gri tüylü küf", "Çiçek salkımlarında ani solma ve kararma"],
        "keywords": ["gri küf", "botrytis", "tüylü küf", "salkım solması"],
        "cause": "Yüksek nemli ortamda yetersiz hava sirkülasyonu.",
        "treatment": "Etkilenen kısımları hemen kesin, nem oranını geçici olarak düşürün ve havalandırmayı artırın. Fungisit uygulayın.",
        "tone": "Gri tüyler nemin çok, havanın az olduğunun işaretidir, bitkinize nefes aldırın."
    }
]
